---
## Load Gapminder

Read in the pandas Gapminder `DataFrame` just like we did in the Lecture 1 notebook. Refer to the DataFrame with the variable `gapminder_data`.  
Display the first 10 rows to confirm it was read correctly.

In [1]:
import pandas as pd
# Load the Gapminder dataset directly from GitHub to ensure Colab out-of-the-box compatibility
url = 'https://raw.githubusercontent.com/jennybc/gapminder/master/inst/extdata/gapminder.tsv'
gapminder_data = pd.read_csv(url, sep='\t')

In [3]:
gapminder_data

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

## Working with Tabular Data: Pandas Exercises with Gapminder
This dataset is the famous [Gapminder dataset](https://www.gapminder.org/data/), containing historical data on life expectancy, population, and GDP per capita for various countries.

Use the pandas skills you learned in *Intro to Data Science* to answer the following descriptive statistics questions. Below each question, write some Python that determines the answer.

Store the value of your solution in the variable 'solution_<number>', eg **```solution_1 = 42```**

####1. How many distinct entries (unique countries) are there in the `country` column?

In [12]:
solution_1 = gapminder_data["country"].nunique()
solution_1

142

#### Unit Test for Problem 1

In [ ]:
assert solution_1 == 142, f"Expected 142 unique countries, got {solution_1}"
print("Unit test for Problem 1 passed!")

####2. What is the most frequent entry in the `continent` column?

In [16]:
solution_2 = gapminder_data["continent"].mode()[0]
solution_2

'Africa'

#### Unit Test for Problem 2

In [ ]:
assert solution_2 == 'Africa', f"Expected 'Africa' as most frequent continent, got {solution_2}"
print("Unit test for Problem 2 passed!")

####3. How many records in the dataset are from the year `2007`?

In [19]:
solution_3 = int((gapminder_data["year"] == 2007).sum())
solution_3

142

#### Unit Test for Problem 3

In [ ]:
assert solution_3 == 142, f"Expected 142 records for year 2007, got {solution_3}"
print("Unit test for Problem 3 passed!")

####4. Create a sub-DataFrame containing only the records where the continent is `Asia`, and only the columns `country`, `year`, and `lifeExp`.

In [22]:
solution_4 = gapminder_data.loc[gapminder_data["continent"] == "Asia", ["country", "year", "lifeExp"]]
solution_4

          country  year  lifeExp
0     Afghanistan  1952   28.801
1     Afghanistan  1957   30.332
2     Afghanistan  1962   31.997
3     Afghanistan  1967   34.020
4     Afghanistan  1972   36.088
...           ...   ...      ...
1675  Yemen, Rep.  1987   52.922
1676  Yemen, Rep.  1992   55.599
1677  Yemen, Rep.  1997   58.020
1678  Yemen, Rep.  2002   60.308
1679  Yemen, Rep.  2007   62.698

[396 rows x 3 columns]

#### Unit Test for Problem 4

In [ ]:
import pandas as pd
assert isinstance(solution_4, pd.DataFrame), "Solution should be a pandas DataFrame"
assert solution_4.shape == (396, 3), f"Expected shape (396, 3), got {solution_4.shape}"
expected_columns = ['country', 'year', 'lifeExp']
assert list(solution_4.columns) == expected_columns, f"Expected columns {expected_columns}, got {list(solution_4.columns)}"
print("Unit test for Problem 4 passed!")

####5. What was the highest life expectancy (`lifeExp`) achieved by a country in `Africa`?

In [30]:
solution_5 = gapminder_data.loc[gapminder_data['continent'] == 'Africa', ['lifeExp']].max()
solution_5 = float(solution_5.iloc[0])
solution_5

76.442

#### Unit Test for Problem 5

In [ ]:
assert abs(solution_5 - 76.442) < 0.001, f"Expected highest life expectancy in Africa around 76.442, got {solution_5}"
print("Unit test for Problem 5 passed!")

####6. Which country in `Europe` had the highest GDP per capita (`gdpPercap`)? Your result should be the **name** of the country.

In [36]:
solution_6 = gapminder_data.loc[gapminder_data['continent'] == 'Europe', ['country','gdpPercap']].sort_values(by='gdpPercap', ascending= False).iloc[0]['country']
solution_6

'Norway'

#### Unit Test for Problem 6

In [ ]:
assert solution_6 == 'Norway', f"Expected 'Norway' as country with highest GDP per capita in Europe, got {solution_6}"
print("Unit test for Problem 6 passed!")

---
####7. Let's now combine several of these data tasks...

You are an economist studying evolution of continental wealth trends. You want to identify the year of maximum difference between GDP per capita in
the Americas and Asia.

In other words, ***which year had the largest gap between average GDP in
the Americas versus Asia***?

Use Python, pandas, and Gapminder dataset to answer this question.

In [75]:
am = gapminder_data.loc[gapminder_data['continent'] == 'Americas', ['country','year','gdpPercap']].groupby('year')["gdpPercap"].mean()
asia = gapminder_data.loc[gapminder_data['continent'] == 'Asia', ['country','year','gdpPercap']].groupby('year')["gdpPercap"].mean()

solution_7 = (asia - am).abs()
solution_7

year
1952    1116.421452
1957    1171.689207
1962     827.827754
1967     302.919878
1972    1696.134560
1977     439.306894
1982      72.601931
1987     185.173753
1992     594.755842
1997     944.792433
2002     886.413289
2007    1469.995245
Name: gdpPercap, dtype: float64

#### Unit Test for Problem 7

In [65]:
assert solution_7 == 1987, f"Expected 1987 as the year with the largest positive difference in average GDP per capita between Americas and Asia, got {solution_7}"
print("Unit test for Problem 7 passed!")

AssertionError: Expected 1987 as the year with the largest positive difference in average GDP per capita between Americas and Asia, got 1972

---